spring:
  datasource:
    username: root
    password: 2022sql
    url: jdbc:mysql://localhost:3306/haha_video?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: false  # avoid warn info
  devtools:
    restart:
      exclude: static/**, application.yml  # 热部署排除的文件
      # enabled: true  # 设置为false关闭
  thymeleaf:
    prefix: classpath:/templates/  # 配置web页面根目录
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            path: /**  # 指定/**表示该文件夹下的所有静态资源都做缓存处理
        cache: true  # 加上缓存配置后我们访问页面后，被加载过的静态资源就会缓存起来，第二次访问时就不会再去重新请求下载了
  messages:  # 国际化配置
    basename: i18n.login
---
logging:
  pattern:
    #格式化，只能输出日期和内容
    console: "%d - %msg%n"
  # 配置日志输出位置
  file:
    path: D:/Java/java_files
#  level: warn  # // 采用这种全局设置级别的方式  只打印 Warn及以上
