spring:
  datasource:
    username: root
    password: 2022sql
    url: jdbc:mysql://localhost:3306/haha_video?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: false  # avoid warn info
  devtools:
    restart:
      exclude: static/**, application.yml  # 热部署排除的文件
      # enabled: true  # 设置为false关闭